# Dockerfile based on the latest centos7 image for non-privileged user entry
#MAINTAINER rajasekhar.kalva@rsrit.com

FROM centos:latest

MAINTAINER rajasekhar.kalva@rsrit.com
RUN useradd -ms /bin/bash raj
USER raj
